export const BASE = 4;
export const PRIMARY_COLOR = '#6698FF';
export const RESIZE_HANDLE_DIAMETER = 9;
export const WithTextPluginKey = 'plait-text-plugin-key';
export const DEFAULT_ROUTE_MARGIN = 30;
export const TRANSPARENT = 'transparent';
export const ROTATE_HANDLE_DISTANCE_TO_ELEMENT = 20;
export const ROTATE_HANDLE_SIZE = 18;
export const DEFAULT_FONT_FAMILY = 'PingFangSC-Regular, "PingFang SC"';
